orgs: ["mouse"] #"human"
mate_length: 150 
paths:
        bb_tools: "/storage1/fs1/martyomov/Active/IndividualBackUps/maksim/tools/bbtools/bbmap"
        data_folder: "/storage1/fs1/martyomov/Active/collaborations/denisk/Tomas_Paulenda/macrophages_treated/HGC20240509004-0058_raw" # path to your fastq files
        result_folder: "/storage1/fs1/martyomov/Active/collaborations/denisk/Tomas_Paulenda/macrophages_treated/HGC20240509004-0058_alignment_result"
        out_dir: "/storage1/fs1/martyomov/Active/collaborations/denisk/Tomas_Paulenda/macrophages_treated"
        human_ref: "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/cellranger/hs/fasta/genome.fa"
        human_gtf: "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/cellranger/hs/genes/genes.gtf"
        mouse_ref: "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/cellranger/mm/fasta/genome.fa"
        mouse_gtf: "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/cellranger/mm/genes/genes.gtf"

        cho_ref: "/scratch1/fs1/martyomov/maksim/permanent/rnaseq/shannon_CHO/cho_ref/data/GCF_003668045.3/FromUcsc/GCF_003668045.3.fa"
        cho_gtf: "/scratch1/fs1/martyomov/maksim/permanent/rnaseq/shannon_CHO/cho_ref/data/GCF_003668045.3/FromUcsc/GCF_003668045.3_CriGri-PICRH-1.0.ncbiRefSeq.gtf"
