org: "mouse" #"human"
mate_length: 150 
paths:
        bb_tools: "/storage1/fs1/martyomov/Active/IndividualBackUps/maksim/tools/bbtools/bbmap"
        data_folder: "/storage1/fs1/martyomov/Active/collaborations/denisk/Tomas_Paulenda/macrophages_treated/HGC20240509004-0058_raw" # path to your fastq files
        result_folder: "/storage1/fs1/martyomov/Active/collaborations/denisk/Tomas_Paulenda/macrophages_treated/HGC20240509004-0058_alignment_result"
        out_dir: "/storage1/fs1/martyomov/Active/collaborations/denisk/Tomas_Paulenda/macrophages_treated"
        genome_files:
                human:
                        ref: "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/cellranger/hs/fasta/genome.fa"
                        gtf: "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/cellranger/hs/genes/genes.gtf"
                mouse:
                        ref: "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/cellranger/mm/fasta/genome.fa"
                        gtf: "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/cellranger/mm/genes/genes.gtf"

        star_preprocessed_files:
                human:
                        sjdbList:  "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/star/hs/sjdbList.fromGTF.out.tab"
                mouse:
                        sjdbList:  "/scratch1/fs1/martyomov/maksim/permanent/scn-pipeline_storage_2/resources/star/mm/sjdbList.fromGTF.out.tab"

